Feature/parser code refactoring
VladiTitov/Octopus.Core pull request #28
Opened 2022-02-13 17:11 UTC by kogonidze

2022-02-14 13:05 UTC, kogonidze commented on Octopus.Core.Common/Extensions/FileInfoExtensions.cs
> +                using (var fs = file.Open(FileMode.Open, FileAccess.Read, FileShare.Read))
Do you mean such syntax?

`using var fs = file.Open(FileMode.Open, FileAccess.Read, FileShare.Read);`

2022-02-14 14:27 UTC, Anton-Sam commented on Octopus.Core.Common/Extensions/FileInfoExtensions.cs
> +                using (var fs = file.Open(FileMode.Open, FileAccess.Read, FileShare.Read))
Yes)

2022-02-14 14:49 UTC, Anton-Sam approved these changes
Good job!

2022-02-15 07:53 UTC, VladiTitov commented on Octopus.Core.Common/Extensions/FileInfoExtensions.cs
> +            }
Maybe `return true;` can be posted here?

2022-02-15 07:53 UTC, VladiTitov commented on Octopus.Core.Common/Extensions/FileInfoExtensions.cs
> +            return true;
and this delete?

2022-02-15 07:55 UTC, VladiTitov commented on Octopus.Core.Parser.BusinessLogic/Interfaces/Services/IParserProcessor.cs
>          Task StartProcessing();
maybe the lines should be swapped for greater readability?

2022-02-15 07:55 UTC, VladiTitov commented on Octopus.Core.Parser.BusinessLogic/Services/MessageHandler.cs
> +                var parserInputData = await _validationService.ValidateEntityDescription(_entityDescription);
good idea!

2022-02-15 07:59 UTC, VladiTitov commented on Octopus.Core.Parser.BusinessLogic/Services/MessageHandler.cs
>                  _entityDescription = JsonSerializer.Deserialize<EntityDescription>(message);
We have special string extention for this. Use this extension

2022-02-15 08:04 UTC, VladiTitov requested changes

2022-02-15 08:04 UTC, VladiTitov commented on Octopus.Core.Common/Extensions/FileInfoExtensions.cs
> +            }
Maybe `return true;` can be posted here?

2022-02-15 08:04 UTC, VladiTitov commented on Octopus.Core.Common/Extensions/FileInfoExtensions.cs
> +            return true;
and this delete?

2022-02-15 08:04 UTC, VladiTitov commented on Octopus.Core.Parser.BusinessLogic/Interfaces/Services/IParserProcessor.cs
>          Task StartProcessing();
maybe the lines should be swapped for greater readability?

2022-02-15 08:04 UTC, VladiTitov commented on Octopus.Core.Parser.BusinessLogic/Services/MessageHandler.cs
>                  _entityDescription = JsonSerializer.Deserialize<EntityDescription>(message);
We have special string extention for this. Use this extension

2022-02-15 12:36 UTC, kogonidze commented on Octopus.Core.Parser.BusinessLogic/Interfaces/Services/IParserProcessor.cs
>          Task StartProcessing();
fixed

2022-02-15 12:36 UTC, kogonidze commented on Octopus.Core.Parser.BusinessLogic/Services/MessageHandler.cs
> +                var parserInputData = await _validationService.ValidateEntityDescription(_entityDescription);
thanks!

2022-02-15 12:49 UTC, kogonidze commented on Octopus.Core.Common/Extensions/FileInfoExtensions.cs
> +            return true;
fixed

2022-02-15 13:37 UTC, VladiTitov approved these changes
Good job!

2022-02-15 14:14 UTC, merged